spring.application.name=employee-svc
server.port=8087

# Database configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/employee-svc?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
logging.level.org.hibernate.persister.entity=ERROR

spring.mvc.hiddenmethod.filter.enabled=true

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.feign=DEBUG

#server.servlet.context-path=/employee-svc
server.shutdown=immediate

#spring.lifecycle.timeout-per-shutdown-phase=20s

